version: '3'
volumes:
  dados:
networks: 
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    volumes: 
      #volume dos dados
      - dados:/var/lib/postgresql/data
      #Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - banco
  frontend:
    image: nginx:1.13
    volumes:
       #Sites
      - ./web:/usr/share/nginx/html/
      #COnfiguração proxy reverso
      - ./nginx/default.config:/etc/nginx/conf.d/default.conf
    networks: 
      - web
    ports:
      - 80:80
    depends_on:
      - app
  app: 
    image: python:3.6
    volumes: 
    #Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment: 
      - DB_NAME=email_sender
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes: 
      # Volumes
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
    